### ISSUE TITLE
Kleines, kleines Problemchen...

### ISSUE THREAD

**Issue by konnekkt** [MCPC10/Arma3-Life-Restart-Script#1]
Guten Morgen Mike, 
zuerst einmal vielen vielen Dank für das Script und die freie Verfügung darüber.
Enschuldigung im Voraus, gibt es eine Möglichkeit den #restart - Befehl ohne Manuelle Eingabe ausführen zu lassen. 

Die Story dahinter: Ich verwende Tadst für meine 5.0 Altis Life Framework, ich bin einfach vertraut mit der Ordnerstrukur und finde es im allgemeinen sehr übersichtlich aufgebaut. Mein Problem ist nur das ich damit keine Auto - Restarts (alle 6h) hinbekomme... Vielleicht kannst du mir einen Tipp geben. 

Steam: http://steamcommunity.com/id/konnekkt oder einfach skiT. 

Entschuldige nochmals das ich auf diese Weise versuche Kontakt mit dir aufzunehmen aber ich bin schon seit Tagen am durchforsten.

Beste Grüße

**Comment by MCPC10** [comment]
Guten Tag xD,
wie du siehst ist das Projekt schon uralt (und netmals mehr aktuell, hab die neuste Version verloren :/). Aber gut, ich kann dir dennoch helfen sowas aufzubauen auf Basis des alten Codes jedoch brauch das dann seine Zeit (hab lange kein SQF mehr gemacht, bin derzeit in C# am programmieren für DaemonMaster (FireDaemon alternative) ). ;)

MfG
MCPC10 / Mike

**Comment by konnekkt** [comment]
Das wäre der Wahnsinn =), vll reicht auch einfach nur eine .Bat aber ich blicke nicht mehr so durch.
Hier mal meine Email: Chilledmelon@gmail.com

Danke dir =)
